### ISSUE TITLE
Issue / PR: Workflows & conventions

### ISSUE THREAD

**Issue by lucido-simon** [do3-2021/gitflow#2]
# What you will find in this issue 
- When to make an Issue
- When to make a PR
- How to make an Issue
- How to make a PR

## When to make an Issue, and what's its goal ?
An issue should be opened when new functional needs are defined, a new bug is discovered, or a documentation resource is going to be created. You **must** open an issue before opening the corresponding branch.  An issue should not be technical, and should describe what the end user will get. You open an issue when either one of the following condition is true :
- You want to describe what your team is currently working on : this issue is meant to be merge from your team's branch to the main branch
- You want to describe features that you are currently working on : this issue is meant to be merge from a feature branch to your team's branch

## How to make an issue ?

The title of the issue should contains :
- Part of the project you're working on ( networking, node agent, ... )
- What it is about in the least amount of words possible ( container health check )
In this example, the title would look like `Node agent: container health check`

The issue should be labeled with either the `feature branch` label, to indicate to others that the issue is meant to be merge into your team's branch. If the issue is meant to be merge to the main branch, then you should label the issue with `enhancement`.

The first few lines of the issue should describe quickly what is the current state of the application, and why there is a need for the issue you are describing. If this is a `enhancement` issue, you should be broad, clear and concise in what you're going to implement and what will change for the end user. If it is a feature branch, the issue should contain less tasks. You can describe them more explicitly.

To describe what you will add to the program, you need to provide a tasks list. For example :
### Tasks list: 
- [x] Create cluster command
- [ ] Delete cluster command

You should tag each tasks with its or their corresponding feature branch.

After creating your issue, if it is a feature issue, you need to create the branch. To the right of the issue in GitHub, you'll find, under `Development`, a button allowing you to `Create a branch`, linked to the issue. You must remove the issue number from the branch name, and you can then click on `create branch`. All work related to this feature issue should be pushed in this branch.

## When to make a PR, and what's its goal ?
There are two kinds of PR you can make : either a feature branch you want to merge into your team's branch, or your team's branch you want to merge into the main branch. Let's begin by the first one, the feature branch :
You should create the PR as soon as you have created the branch for your issue. 

## How to make a PR ?

The title of the PR should be in the form of `<team-name>:<short-description>`
For example : `Node agent: container health check`. The name should be similar or even identical to its related issue.

You should first give a quick explanation of your works, the technical decisions you are making / you made, and why. Don't hesitate to aerate your explanation.

The PR must have the same task list that the issue, except that each tasks will have sub-tasks, who are technical.

### Tasks list:
- [x] Create cluster command
    - [x] Command line parsing
    - [x] Understanding what the user wants
    - [x] Calling relevant API endpoints
    - [x] Dealing with errors
- [ ] Delete cluster command
    - [ ] Command line parsing
    - [ ] Understanding what the user wants
    - [x] Calling relevant API endpoints
    - [ ] Dealing with errors

At the bottom of the PR, you should link the issue this PR solves : `Close: #15` . Click [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for more information.
